In [1]:
import numpy as np
from collections import Counter

In [2]:
import pandas as pd
import math

In [3]:
from sklearn import datasets

In [4]:
iris=datasets.load_iris()

In [5]:
data=iris.data
target=iris.target

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
x_train,x_test,y_train,y_test=train_test_split(data,target,test_size=0.2)

In [8]:
x_train.shape

(120, 4)

In [9]:
x_test.shape

(30, 4)

In [10]:
k=6
count1=0;
for i in range(x_test.shape[0]):
    dict1={}
    for j in range(x_train.shape[0]):
        dist=((x_test[i]-x_train[j])**2).sum()
        dist=math.sqrt(dist)
        dict1[dist]=y_train[j]
    dict1=sorted(dict1.items())
    votes=[]
    for p in range(k):
        votes.append(dict1[p][1])
    v=Counter(votes).most_common(1)[0][0]
    if(v==y_test[i]):
        count1+=1
    print("Predicted: ",v,"Actual: ",y_test[i])

Predicted:  0 Actual:  0
Predicted:  2 Actual:  2
Predicted:  0 Actual:  0
Predicted:  1 Actual:  1
Predicted:  0 Actual:  0
Predicted:  2 Actual:  2
Predicted:  1 Actual:  1
Predicted:  0 Actual:  0
Predicted:  0 Actual:  0
Predicted:  0 Actual:  0
Predicted:  2 Actual:  2
Predicted:  1 Actual:  1
Predicted:  2 Actual:  2
Predicted:  2 Actual:  2
Predicted:  2 Actual:  2
Predicted:  1 Actual:  1
Predicted:  2 Actual:  2
Predicted:  0 Actual:  0
Predicted:  0 Actual:  0
Predicted:  2 Actual:  1
Predicted:  1 Actual:  1
Predicted:  0 Actual:  0
Predicted:  1 Actual:  1
Predicted:  2 Actual:  2
Predicted:  0 Actual:  0
Predicted:  1 Actual:  1
Predicted:  2 Actual:  2
Predicted:  1 Actual:  1
Predicted:  0 Actual:  0
Predicted:  1 Actual:  1


In [11]:
accuracy=count1/x_test.shape[0]


In [12]:
accuracy

0.9666666666666667

In [13]:
count1

29

In [14]:
x_test.shape

(30, 4)

In [15]:
clusters=3

In [16]:
from sklearn.cluster import KMeans

In [17]:
clf1=KMeans(n_clusters=3)

In [18]:
clf1.fit(x_train,y_train)

KMeans(algorithm='auto', copy_x=True, init='k-means++', max_iter=300,
    n_clusters=3, n_init=10, n_jobs=1, precompute_distances='auto',
    random_state=None, tol=0.0001, verbose=0)

In [19]:
clf1.cluster_centers_

array([[5.914     , 2.726     , 4.394     , 1.424     ],
       [6.82580645, 3.05806452, 5.72903226, 2.06774194],
       [5.01025641, 3.45641026, 1.46410256, 0.24358974]])

In [20]:
clf1.predict(x_test)

array([2, 0, 2, 0, 2, 1, 0, 2, 2, 2, 1, 0, 1, 0, 1, 0, 1, 2, 2, 0, 0, 2,
       0, 0, 2, 1, 1, 0, 2, 0], dtype=int32)

In [23]:
x=data

In [24]:
flag=1


In [25]:
count1=0
c1=x_train[0]
c2=x_train[1]
c3=x_train[2]
while(count1<=10):
    list1=[]
    list2=[]
    list3=[]
    for i in range(x.shape[0]):
        dist1=((x[i]-c1)**2).sum()
        dist2=((x[i]-c2)**2).sum()
        dist3=((x[i]-c3)**2).sum()
#         print(dist1," ",dist2," ",dist3)
        if(dist1<=dist2 and dist1<=dist3):
            point=dist1
            list1.append(x[i])
        if(dist2<=dist3 and dist2<=dist1):
            point=dist2
            list2.append(x[i])
        if(dist3<=dist2 and dist3<=dist1):
            point=dist3
            list3.append(x[i])
    cl1=[]
    cl2=[]
    cl3=[]
    cl4=[]
    
    for i in list1:
        cl1.append(i[0])
        cl2.append(i[1])
        cl3.append(i[2])
        cl4.append(i[3])
#         print(i)
    new1=sum(cl1)/(len(cl1)+1)
    new2=sum(cl2)/(len(cl2)+1)
    new3=sum(cl3)/(len(cl3)+1)
    new4=sum(cl4)/(len(cl4)+1)
    newpoint1=[new1,new2,new3,new4]
    
    
    cl1=[]
    cl2=[]
    cl3=[]
    cl4=[]
    
    for i in list2:
        cl1.append(i[0])
        cl2.append(i[1])
        cl3.append(i[2])
        cl4.append(i[3])
#         print(cl1)
    new1=sum(cl1)/(len(cl1)+1)
    new2=sum(cl2)/(len(cl2)+1)
    new3=sum(cl3)/(len(cl3)+1)
    new4=sum(cl4)/(len(cl4)+1)
    newpoint2=[new1,new2,new3,new4]
    
    cl1=[]
    cl2=[]
    cl3=[]
    cl4=[]
    
    for i in list3:
        cl1.append(i[0])
        cl2.append(i[1])
        cl3.append(i[2])
        cl4.append(i[3])
    new1=sum(cl1)/(len(cl1)+1)
    new2=sum(cl2)/(len(cl2)+1)
    new3=sum(cl3)/(len(cl3)+1)
    new4=sum(cl4)/(len(cl4)+1)
    newpoint3=[new1,new2,new3,new4]
    print(c1," ",c2," ",c3)
    c1=newpoint1
    c2=newpoint2
    c3=newpoint3
    print(c1," ",c2," ",c3)


    print()
    count1+=1;
            
        
            
            
        
        
    
    
    
    

[6.5 3.  5.5 1.8]   [5.6 3.  4.5 1.5]   [6.1 2.6 5.6 1.4]
[6.63695652173913, 2.9804347826086954, 5.478260869565216, 1.978260869565217]   [5.352000000000001, 3.056000000000001, 2.81, 0.7899999999999997]   [5.142857142857143, 2.2, 4.4, 1.4000000000000001]

[6.63695652173913, 2.9804347826086954, 5.478260869565216, 1.978260869565217]   [5.352000000000001, 3.056000000000001, 2.81, 0.7899999999999997]   [5.142857142857143, 2.2, 4.4, 1.4000000000000001]
[6.5107692307692275, 2.9661538461538464, 5.267692307692308, 1.8599999999999994]   [4.939285714285715, 3.2785714285714294, 1.6053571428571427, 0.3142857142857142]   [5.521874999999998, 2.553125, 4.109375, 1.2906250000000001]

[6.5107692307692275, 2.9661538461538464, 5.267692307692308, 1.8599999999999994]   [4.939285714285715, 3.2785714285714294, 1.6053571428571427, 0.3142857142857142]   [5.521874999999998, 2.553125, 4.109375, 1.2906250000000001]
[6.484848484848482, 2.9454545454545453, 5.27878787878788, 1.8742424242424238]   [4.907843137254901, 

In [26]:
c1

[6.473529411764703, 2.944117647058824, 5.260294117647059, 1.8573529411764702]

In [27]:
c2

[4.907843137254901,
 3.3509803921568633,
 1.4352941176470588,
 0.23921568627450973]

In [28]:
c3

[5.470588235294117, 2.5588235294117645, 3.908823529411765, 1.214705882352941]

In [29]:
y=target

In [30]:
list1=[]
list2=[]
list3=[]
for i in range(x.shape[0]):
        dist1=((x[i]-c1)**2).sum()
        dist2=((x[i]-c2)**2).sum()
        dist3=((x[i]-c3)**2).sum()
#         print(dist1," ",dist2," ",dist3)
        if(dist1<dist2 and dist1<dist3):
            print(y[i]," 0")
        elif(dist2<dist1 and dist2<dist3):
            print(y[i]," 1")
        else:
            print(y[i]," 2")

0  1
0  1
0  1
0  1
0  1
0  1
0  1
0  1
0  1
0  1
0  1
0  1
0  1
0  1
0  1
0  1
0  1
0  1
0  1
0  1
0  1
0  1
0  1
0  1
0  1
0  1
0  1
0  1
0  1
0  1
0  1
0  1
0  1
0  1
0  1
0  1
0  1
0  1
0  1
0  1
0  1
0  1
0  1
0  1
0  1
0  1
0  1
0  1
0  1
0  1
1  0
1  0
1  0
1  2
1  0
1  2
1  0
1  2
1  0
1  2
1  2
1  2
1  2
1  0
1  2
1  0
1  2
1  2
1  2
1  2
1  0
1  2
1  0
1  0
1  2
1  0
1  0
1  0
1  2
1  2
1  2
1  2
1  2
1  0
1  2
1  0
1  0
1  2
1  2
1  2
1  2
1  0
1  2
1  2
1  2
1  2
1  2
1  2
1  2
1  2
2  0
2  0
2  0
2  0
2  0
2  0
2  2
2  0
2  0
2  0
2  0
2  0
2  0
2  0
2  0
2  0
2  0
2  0
2  0
2  0
2  0
2  0
2  0
2  0
2  0
2  0
2  0
2  0
2  0
2  0
2  0
2  0
2  0
2  0
2  0
2  0
2  0
2  0
2  0
2  0
2  0
2  0
2  0
2  0
2  0
2  0
2  0
2  0
2  0
2  0
